image: maven:3-jdk-8

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PROFILE_OPTS: "-P syntaxphoenix"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install $PROFILE_OPTS $MAVEN_OPTS $MAVEN_ADDITION

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy $PROFILE_OPTS $MAVEN_OPTS -Dmaven.test.skip=true -Dmaven.main.skip=true $MAVEN_ADDITION
  only:
    refs:
      - master
