image: maven:3-jdk-8

stages:
  - gpg
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -P$MAVEN_PROFILE --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
job:
  stage: gpg
  except:
    variables:
      - $MAVEN_PROFILE == "syntaxphoenix"
  before_script:
    - gpg --no-tty --batch --yes --passphrase $GPG_PASSPHRASE --import $GPG_SECRET_KEY

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true $MAVEN_ADDITION
  only:
    branches:
      - master
    variables:
      - ($CI_COMMIT_MESSAGE =~ /^(?<tag>[publish])\s*(?<content>.*)\s*$/gim) || ($MAVEN_PROFILE == "syntaxphoenix")
