image: maven:3-jdk-8

stages:
  - gpg
  - profiles
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PROFILE_OPTS: "-P $MAVEN_PROFILE"

cache:
  paths:
    - .m2/repository/
    - target/

gpg:
  stage: gpg
  script:
    - gpg --no-tty --batch --yes --passphrase $GPG_PASSPHRASE --import $GPG_SECRET_KEY
  except:
    variables:
      - $MAVEN_PROFILE == "syntaxphoenix"

profiles:
  stage: profiles
  script:
    - mvn $MAVEN_CLI_OPTS help:active-profiles $PROFILE_OPTS $MAVEN_ADDITION

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install $PROFILE_OPTS $MAVEN_ADDITION
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy $PROFILE_OPTS -Dmaven.test.skip=true -Dmaven.main.skip=true $MAVEN_ADDITION
  only:
    refs:
      - master
    variables:
      - ($CI_COMMIT_MESSAGE =~ /^(?P<name>\[publish\]).*$/) || ($MAVEN_PROFILE == "syntaxphoenix")