image: maven:3-jdk-8

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PROFILE_OPTS: "-P $MAVEN_PROFILE"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  before_script:
    - $BEFORE_SCRIPT
  script:
    - mvn $MAVEN_CLI_OPTS clean install $PROFILE_OPTS $MAVEN_ADDITION
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy $PROFILE_OPTS -Dmaven.test.skip=true -Dmaven.main.skip=true $MAVEN_ADDITION
  only:
    refs:
      - master
    variables:
      - ($CI_COMMIT_MESSAGE =~ /^(?P<name>\[publish\]).*$/) || ($MAVEN_PROFILE == "syntaxphoenix")